package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Abastecimentos generated by hbm2java
 */
public class Abastecimento  implements java.io.Serializable {


     private Integer id;
     private int competencia;
     private Date dataabastecimento;
     private float quantidade;
     private Usuario usuarioinclusao;
     private Date datainclusao;
     private Usuario usuarioalteracao;
     private Date dataalteracao;

    public Abastecimento() {
    }
	
    public Abastecimento(int competencia, Date dataabastecimento, float quantidade, Usuario usuarioinclusao, Date datainclusao) {
        this.competencia = competencia;
        this.dataabastecimento = dataabastecimento;
        this.quantidade = quantidade;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }

    public Abastecimento(int competencia, Date dataabastecimento, float quantidade, Usuario usuarioinclusao, Date datainclusao, Usuario usuarioalteracao, Date dataalteracao) {
       this.competencia = competencia;
       this.dataabastecimento = dataabastecimento;
       this.quantidade = quantidade;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public int getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(int competencia) {
        this.competencia = competencia;
    }

    public Date getDataabastecimento() {
        return this.dataabastecimento;
    }
    
    public void setDataabastecimento(Date dataabastecimento) {
        this.dataabastecimento = dataabastecimento;
    }

    public float getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(float quantidade) {
        this.quantidade = quantidade;
    }

    public Usuario getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(Usuario usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }

    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }

    public Usuario getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Usuario usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }

    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


