package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Competencias generated by hbm2java
 */
public class Competencia  implements java.io.Serializable {


     private Integer id;
     private Condominio condominio;
     private Competencia competencia;
     private boolean situacao;
     private Usuario usuarioinclusao;
     private Date datainclusao;
     private Usuario usuarioalteracao;
     private Date dataalteracao;

    public Competencia() {
    }
	
    public Competencia(Condominio condominio, Competencia competencia, boolean situacao, Usuario usuarioinclusao, Date datainclusao) {
        this.condominio = condominio;
        this.competencia = competencia;
        this.situacao = situacao;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }

    public Competencia(Condominio condominio, Competencia competencia, boolean situacao, Usuario usuarioinclusao, Date datainclusao, Usuario usuarioalteracao, Date dataalteracao) {
       this.condominio = condominio;
       this.competencia = competencia;
       this.situacao = situacao;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Condominio getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(Condominio condominio) {
        this.condominio = condominio;
    }

    public Competencia getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(Competencia competencia) {
        this.competencia = competencia;
    }

    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

    public Usuario getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(Usuario usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }

    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }

    public Usuario getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Usuario usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }

    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


