package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Competencias generated by hbm2java
 */
public class Competencias  implements java.io.Serializable {


     private Integer id;
     private int condominio;
     private Date competencia;
     private boolean situacao;
     private int usuarioinclusao;
     private Date datainclusao;
     private Integer usuarioalteracao;
     private Date dataalteracao;

    public Competencias() {
    }

	
    public Competencias(int condominio, Date competencia, boolean situacao, int usuarioinclusao, Date datainclusao) {
        this.condominio = condominio;
        this.competencia = competencia;
        this.situacao = situacao;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }
    public Competencias(int condominio, Date competencia, boolean situacao, int usuarioinclusao, Date datainclusao, Integer usuarioalteracao, Date dataalteracao) {
       this.condominio = condominio;
       this.competencia = competencia;
       this.situacao = situacao;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(int condominio) {
        this.condominio = condominio;
    }
    public Date getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(Date competencia) {
        this.competencia = competencia;
    }
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }
    public int getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(int usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    public Integer getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Integer usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }




}


