package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Condominios generated by hbm2java
 */
public class Condominio  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String cnpj;
     private String endereco;
     private String email;
     private Usuario usuarioInclusao;
     private Date dataInclusao;
     private Usuario usuarioAlteracao;
     private Date dataAlteracao;

    public Condominio() {
    }
	
    public Condominio(String nome, String cnpj, String endereco, Usuario usuarioInclusao, Date dataInclusao) {
        this.nome = nome;
        this.cnpj = cnpj;
        this.endereco = endereco;
        this.usuarioInclusao = usuarioInclusao;
        this.dataInclusao = dataInclusao;
    }

    public Condominio(String nome, String cnpj, String endereco, String email, Usuario usuarioInclusao, Date dataInclusao, Usuario usuarioAlteracao, Date dataAlteracao) {
       this.nome = nome;
       this.cnpj = cnpj;
       this.endereco = endereco;
       this.email = email;
       this.usuarioInclusao = usuarioInclusao;
       this.dataInclusao = dataInclusao;
       this.usuarioAlteracao = usuarioAlteracao;
       this.dataAlteracao = dataAlteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Usuario getUsuarioinclusao() {
        return this.usuarioInclusao;
    }
    
    public void setUsuarioinclusao(Usuario usuarioinclusao) {
        this.usuarioInclusao = usuarioinclusao;
    }

    public Date getDatainclusao() {
        return this.dataInclusao;
    }
    
    public void setDatainclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }

    public Usuario getUsuarioalteracao() {
        return this.usuarioAlteracao;
    }
    
    public void setUsuarioalteracao(Usuario usuarioIlteracao) {
        this.usuarioAlteracao = usuarioAlteracao;
    }

    public Date getDataalteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataalteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }

}


