package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Leituras generated by hbm2java
 */
public class Leituras  implements java.io.Serializable {


     private Integer id;
     private int unidadeconsumidora;
     private int competencia;
     private Date dataleitura;
     private float remessas;
     private Float consumo;
     private int usuarioinclusao;
     private Date datainclusao;
     private Integer usuarioalteracao;
     private Date dataalteracao;

    public Leituras() {
    }

	
    public Leituras(int unidadeconsumidora, int competencia, Date dataleitura, float remessas, int usuarioinclusao, Date datainclusao) {
        this.unidadeconsumidora = unidadeconsumidora;
        this.competencia = competencia;
        this.dataleitura = dataleitura;
        this.remessas = remessas;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }
    public Leituras(int unidadeconsumidora, int competencia, Date dataleitura, float remessas, Float consumo, int usuarioinclusao, Date datainclusao, Integer usuarioalteracao, Date dataalteracao) {
       this.unidadeconsumidora = unidadeconsumidora;
       this.competencia = competencia;
       this.dataleitura = dataleitura;
       this.remessas = remessas;
       this.consumo = consumo;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUnidadeconsumidora() {
        return this.unidadeconsumidora;
    }
    
    public void setUnidadeconsumidora(int unidadeconsumidora) {
        this.unidadeconsumidora = unidadeconsumidora;
    }
    public int getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(int competencia) {
        this.competencia = competencia;
    }
    public Date getDataleitura() {
        return this.dataleitura;
    }
    
    public void setDataleitura(Date dataleitura) {
        this.dataleitura = dataleitura;
    }
    public float getRemessas() {
        return this.remessas;
    }
    
    public void setRemessas(float remessas) {
        this.remessas = remessas;
    }
    public Float getConsumo() {
        return this.consumo;
    }
    
    public void setConsumo(Float consumo) {
        this.consumo = consumo;
    }
    public int getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(int usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    public Integer getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Integer usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }




}


