package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Mandatos generated by hbm2java
 */
public class Mandato  implements java.io.Serializable {


     private int id;
     private int sindico;
     private int condominio;
     private Date mandatoinicio;
     private Date mandatofim;
     private Usuario usuarioinclusao;
     private Date datainclusao;
     private Usuario usuarioalteracao;
     private Date dataalteracao;

    public Mandato() {
    }

    public Mandato(int id, int sindico, int condominio, Date mandatoinicio, Date mandatofim, Usuario usuarioinclusao, Date datainclusao) {
        this.id = id;
        this.sindico = sindico;
        this.condominio = condominio;
        this.mandatoinicio = mandatoinicio;
        this.mandatofim = mandatofim;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }
    
    public Mandato(int id, int sindico, int condominio, Date mandatoinicio, Date mandatofim, Usuario usuarioinclusao, Date datainclusao, Usuario usuarioalteracao, Date dataalteracao) {
       this.id = id;
       this.sindico = sindico;
       this.condominio = condominio;
       this.mandatoinicio = mandatoinicio;
       this.mandatofim = mandatofim;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public int getSindico() {
        return this.sindico;
    }
    
    public void setSindico(int sindico) {
        this.sindico = sindico;
    }
    
    public int getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(int condominio) {
        this.condominio = condominio;
    }
    
    public Date getMandatoinicio() {
        return this.mandatoinicio;
    }
    
    public void setMandatoinicio(Date mandatoinicio) {
        this.mandatoinicio = mandatoinicio;
    }
    
    public Date getMandatofim() {
        return this.mandatofim;
    }
    
    public void setMandatofim(Date mandatofim) {
        this.mandatofim = mandatofim;
    }
    
    public Usuario getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(Usuario usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    
    public Usuario getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Usuario usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


