package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Medidores generated by hbm2java
 */
public class Medidores  implements java.io.Serializable {


     private Integer id;
     private int condominio;
     private int tipomedidor;
     private String numeroserie;
     private Date dataaquisicao;
     private int usuarioinclusao;
     private Date datainclusao;
     private Integer usuarioalteracao;
     private Date dataalteracao;

    public Medidores() {
    }

    public Medidores(int condominio, int tipomedidor, String numeroserie, Date dataaquisicao, int usuarioinclusao, Date datainclusao) {
        this.condominio = condominio;
        this.tipomedidor = tipomedidor;
        this.numeroserie = numeroserie;
        this.dataaquisicao = dataaquisicao;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }

    public Medidores(int condominio, int tipomedidor, String numeroserie, Date dataaquisicao, int usuarioinclusao, Date datainclusao, Integer usuarioalteracao, Date dataalteracao) {
       this.condominio = condominio;
       this.tipomedidor = tipomedidor;
       this.numeroserie = numeroserie;
       this.dataaquisicao = dataaquisicao;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public int getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(int condominio) {
        this.condominio = condominio;
    }
    
    public int getTipomedidor() {
        return this.tipomedidor;
    }
    
    public void setTipomedidor(int tipomedidor) {
        this.tipomedidor = tipomedidor;
    }
    
    public String getNumeroserie() {
        return this.numeroserie;
    }
    
    public void setNumeroserie(String numeroserie) {
        this.numeroserie = numeroserie;
    }
    
    public Date getDataaquisicao() {
        return this.dataaquisicao;
    }
    
    public void setDataaquisicao(Date dataaquisicao) {
        this.dataaquisicao = dataaquisicao;
    }
    
    public int getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(int usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    
    public Integer getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Integer usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


