package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Medidoresucs generated by hbm2java
 */
public class Medidoruc  implements java.io.Serializable {


     private Integer id;
     private UnidadeConsumidora unidadeconsumidora;
     private int medidor;
     private Date datainstalacao;
     private Date dataretirada;
     private Usuario usuarioinclusao;
     private Date datainclusao;
     private Usuario usuarioalteracao;
     private Date dataalteracao;

    public Medidoruc() {
    }
	
    public Medidoruc(UnidadeConsumidora unidadeconsumidora, int medidor, Date datainstalacao, Usuario usuarioinclusao, Date datainclusao) {
        this.unidadeconsumidora = unidadeconsumidora;
        this.medidor = medidor;
        this.datainstalacao = datainstalacao;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }
    
    public Medidoruc(UnidadeConsumidora unidadeconsumidora, int medidor, Date datainstalacao, Date dataretirada, Usuario usuarioinclusao, Date datainclusao, Usuario usuarioalteracao, Date dataalteracao) {
       this.unidadeconsumidora = unidadeconsumidora;
       this.medidor = medidor;
       this.datainstalacao = datainstalacao;
       this.dataretirada = dataretirada;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public UnidadeConsumidora getUnidadeconsumidora() {
        return this.unidadeconsumidora;
    }
    
    public void setUnidadeconsumidora(UnidadeConsumidora unidadeconsumidora) {
        this.unidadeconsumidora = unidadeconsumidora;
    }
    
    public int getMedidor() {
        return this.medidor;
    }
    
    public void setMedidor(int medidor) {
        this.medidor = medidor;
    }
    
    public Date getDatainstalacao() {
        return this.datainstalacao;
    }
    
    public void setDatainstalacao(Date datainstalacao) {
        this.datainstalacao = datainstalacao;
    }
    
    public Date getDataretirada() {
        return this.dataretirada;
    }
    
    public void setDataretirada(Date dataretirada) {
        this.dataretirada = dataretirada;
    }
    
    public Usuario getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(Usuario usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    
    public Usuario getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Usuario usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


