package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Retorno generated by hbm2java
 */
public class Retorno  implements java.io.Serializable {


     private int id;
     private int ocorrencia;
     private int remessa;
     private Date dataleitura;
     private int consumo;
     private float leitura;
     private int usuarioinclusao;
     private Date datainclusao;
     private Integer usuarioalteracao;
     private Date dataalteracao;

    public Retorno() {
    }
	
    public Retorno(int id, int ocorrencia, int remessa, Date dataleitura, int consumo, float leitura, int usuarioinclusao, Date datainclusao) {
        this.id = id;
        this.ocorrencia = ocorrencia;
        this.remessa = remessa;
        this.dataleitura = dataleitura;
        this.consumo = consumo;
        this.leitura = leitura;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }
    
    public Retorno(int id, int ocorrencia, int remessa, Date dataleitura, int consumo, float leitura, int usuarioinclusao, Date datainclusao, Integer usuarioalteracao, Date dataalteracao) {
       this.id = id;
       this.ocorrencia = ocorrencia;
       this.remessa = remessa;
       this.dataleitura = dataleitura;
       this.consumo = consumo;
       this.leitura = leitura;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public int getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(int ocorrencia) {
        this.ocorrencia = ocorrencia;
    }
    
    public int getRemessa() {
        return this.remessa;
    }
    
    public void setRemessa(int remessa) {
        this.remessa = remessa;
    }
    
    public Date getDataleitura() {
        return this.dataleitura;
    }
    
    public void setDataleitura(Date dataleitura) {
        this.dataleitura = dataleitura;
    }
    
    public int getConsumo() {
        return this.consumo;
    }
    
    public void setConsumo(int consumo) {
        this.consumo = consumo;
    }
    
    public float getLeitura() {
        return this.leitura;
    }
    
    public void setLeitura(float leitura) {
        this.leitura = leitura;
    }
    
    public int getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(int usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    
    public Integer getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Integer usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


