package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tiposuc generated by hbm2java
 */
public class Tiposuc  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private int usuarioinclusao;
     private Date datainclusao;
     private Integer usuarioalteracao;
     private Date dataalteracao;

    public Tiposuc() {
    }
	
    public Tiposuc(String nome, int usuarioinclusao, Date datainclusao) {
        this.nome = nome;
        this.usuarioinclusao = usuarioinclusao;
        this.datainclusao = datainclusao;
    }
    
    public Tiposuc(String nome, int usuarioinclusao, Date datainclusao, Integer usuarioalteracao, Date dataalteracao) {
       this.nome = nome;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    public int getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(int usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    
    public Integer getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Integer usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


