package br.com.xkinfo.slc.Model;
// Generated 13/07/2014 22:14:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Unidadeconsumidora generated by hbm2java
 */
public class Unidadeconsumidora  implements java.io.Serializable {


     private Integer id;
     private int condominio;
     private int tipouc;
     private boolean ultimonovel;
     private Integer nivelsuperior;
     private int numero;
     private Date dataultimaleitura;
     private int usuarioinclusao;
     private Date datainclusao;
     private Integer usuarioalteracao;
     private Date dataalteracao;

    public Unidadeconsumidora() {
    }
	
    public Unidadeconsumidora(int condominio, int tipouc, boolean ultimonovel, int numero, int usuarioinclusao, Date datainclusao) {
        this.condominio = condominio;
        this.tipouc = tipouc;
        this.ultimonovel = ultimonovel;
        this.numero = numero;
        this.usuarioinclusao = usuarioinclusao;
    }
        
    public Unidadeconsumidora(int condominio, int tipouc, boolean ultimonovel, Integer nivelsuperior, int numero, Date dataultimaleitura, int usuarioinclusao, Date datainclusao, Integer usuarioalteracao, Date dataalteracao) {
       this.condominio = condominio;
       this.tipouc = tipouc;
       this.ultimonovel = ultimonovel;
       this.nivelsuperior = nivelsuperior;
       this.numero = numero;
       this.dataultimaleitura = dataultimaleitura;
       this.usuarioinclusao = usuarioinclusao;
       this.datainclusao = datainclusao;
       this.usuarioalteracao = usuarioalteracao;
       this.dataalteracao = dataalteracao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public int getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(int condominio) {
        this.condominio = condominio;
    }
    
    public int getTipouc() {
        return this.tipouc;
    }
    
    public void setTipouc(int tipouc) {
        this.tipouc = tipouc;
    }
    
    public boolean isUltimonovel() {
        return this.ultimonovel;
    }
    
    public void setUltimonovel(boolean ultimonovel) {
        this.ultimonovel = ultimonovel;
    }
    
    public Integer getNivelsuperior() {
        return this.nivelsuperior;
    }
    
    public void setNivelsuperior(Integer nivelsuperior) {
        this.nivelsuperior = nivelsuperior;
    }
    
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    
    public Date getDataultimaleitura() {
        return this.dataultimaleitura;
    }
    
    public void setDataultimaleitura(Date dataultimaleitura) {
        this.dataultimaleitura = dataultimaleitura;
    }
    
    public int getUsuarioinclusao() {
        return this.usuarioinclusao;
    }
    
    public void setUsuarioinclusao(int usuarioinclusao) {
        this.usuarioinclusao = usuarioinclusao;
    }
    
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    
    public Integer getUsuarioalteracao() {
        return this.usuarioalteracao;
    }
    
    public void setUsuarioalteracao(Integer usuarioalteracao) {
        this.usuarioalteracao = usuarioalteracao;
    }
    
    public Date getDataalteracao() {
        return this.dataalteracao;
    }
    
    public void setDataalteracao(Date dataalteracao) {
        this.dataalteracao = dataalteracao;
    }

}


